name: DebugBuild

on:
  push:
    branches:
      - master

env:
  SOLUTION_FILE_PATH: SHEngine.sln
  CONFIGURATION: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add MSBuild to Path
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      # CMake 4.2.x のセットアップを追加
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.2.x'

      # Setup.batを起動する
      - name: Run setup.bat
        run: .\setup.bat
        shell: cmd

      - name: Build
        run: msbuild ${{ env.SOLUTION_FILE_PATH }} /p:Platform=x64 /p:Configuration=${{ env.CONFIGURATION }}